---
- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Setup local users ssh keys
  ansible.builtin.include_tasks: ssh_user.yml
  with_dict: '{{ users }}'
  loop_control:
    loop_var: local_user_data

- name: Setup local users ssh keys from github
  ansible.builtin.include_tasks: github_user.yml
  with_dict: '{{ github_users }}'
  loop_control:
    loop_var: local_user_data

- name: optionally remove existing ssh keys to make sure you there are no wrong keys
  ansible.builtin.include_tasks: delete_keys.yml
  when: manage_all_keys | bool

- name: Setup ssh keys for admin users
  ansible.builtin.include_tasks: ssh_root.yml
  with_dict: '{{ users }}'
  loop_control:
    loop_var: local_user_data

- name: Set authorized keys from admins for user root
  become: true
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  when: grant_special_ssh_root_access | bool
  with_items: "{{ root_ssh_keys }}"
