---
- name: Find SSH Key store for "{{ ssh_user_data }}"
  ansible.builtin.set_fact:
    keys: "{{ lookup('fileglob', '{{ ssh_public_key_store }}/{{ ssh_user_data }}*_*.pub') }}"

- name: Set authorized key "{{ ssh_user_data }}" for user ansible
  become: true
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '{{ keys }}') }}"
  changed_when: false

- name: Set authorized key "{{ ssh_user_data }}" for user root
  become: true
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '{{ keys }}') }}"
    key_options: "no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command=\"echo '{{ ssh_root_login_warning }}';echo;sleep 10\""
  when: restict_ssh_root_access | bool
  changed_when: false

- name: Set authorized key "{{ ssh_user_data }}" for user root
  become: true
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '{{ keys }}') }}"
  changed_when: false
  when: not restict_ssh_root_access | bool
