---
- name: Extract local and remote user names
  ansible.builtin.set_fact:
    local_user: '{{ local_user_data.name }}'
    pubkeys: '{{ local_user_data.keys }}'

- name: 'Add ssh keys for user {{ local_user }}'
  become: true
  ansible.posix.authorized_key:
    user: '{{ local_user }}'
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ pubkeys }}"

- name: 'Add github ssh keys for user ansible'
  become: true
  ansible.posix.authorized_key:
    user: 'ansible'
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ pubkeys }}"
  when: local_user in admins
